In [ ]:
import numpy as np


# 1D
arr1 = np.array([1, 2, 3, 4])


# 2D
arr2 = np.array([[1, 2, 3],
[4, 5, 6]])

# 3D
arr3 = np.array([
[[1, 2], [3, 4]],
[[5, 6], [7, 8]]
])

In [ ]:
import torch


# 1D
t1 = torch.tensor([1, 2, 3, 4])


# 2D
t2 = torch.tensor([[1, 2, 3],
[4, 5, 6]])


# 3D
t3 = torch.tensor([
[[1, 2], [3, 4]],
[[5, 6], [7, 8]]
])

In [ ]:
# NumPy
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


print(a + b)
print(a * b)
print(a ** 2)


# PyTorch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])


print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]
tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([1, 4, 9])


In [ ]:
# NumPy
A = np.array([[10,20,30],[40,50,60]])
print(A[0, 1]) # 20
print(A[:, 1]) # column

# PyTorch
T = torch.tensor([[10,20,30],[40,50,60]])
print(T[0, 1])
print(T[:, 1])

20
[20 50]
tensor(20)
tensor([20, 50])


In [ ]:
# NumPy
x = np.array([1, 2, 3, 4, 5])
mask = x > 3
print(x[mask])

# PyTorch
x = torch.tensor([1, 2, 3, 4, 5])
mask = x > 3
print(x[mask])

[4 5]
tensor([4, 5])


In [ ]:
# NumPy
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
sub = M[0:2, 1:3]

# PyTorch
M = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
sub = M[0:2, 1:3]

In [ ]:
t = torch.arange(12)
print("Original t:", t)
print("Original shape:", t.shape)


# view (only works if memory is contiguous)
t_view = t.view(3, 4)
print("After view(3,4):")
print(t_view)
print("Shape:", t_view.shape)


# reshape (safe version)
t_reshape = t.reshape(3, 4)
print("After reshape(3,4):")
print(t_reshape)
print("Shape:", t_reshape.shape)


# unsqueeze (add dimension)
t_unsq = t.unsqueeze(0) # shape: (1, 12)
print("After unsqueeze(0):")
print(t_unsq)
print("Shape:", t_unsq.shape)


# squeeze (remove dim size=1)
t_sq = t_unsq.squeeze() # shape: (12,)
print("After squeeze():")
print(t_sq)
print("Shape:", t_sq.shape)

Original t: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])
After view(3,4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])
After reshape(3,4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])
After unsqueeze(0):
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
Shape: torch.Size([1, 12])
After squeeze():
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])


In [ ]:
arr = np.arange(12)
arr_r = arr.reshape(3, 4)
print(arr_r)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# NumPy
A = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print(A + b)

# PyTorch
A = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([10,20,30])
print(A + b)

[[11 22 33]
 [14 25 36]]
tensor([[11, 22, 33],
        [14, 25, 36]])


In [ ]:
x = np.array([1., 2., 3.])


y = x + 1 # Out-of-place
x += 1 # In-place



x = torch.tensor([1., 2., 3.])


y = x + 1 # Out-of-place
x.add_(1) # In-place (underscore)

tensor([2., 3., 4.])